portfolio_project/portfolio_app/urls.py
from django.urls import path
from . import views
from .views import ContactView

app_name = "portfolio_app"

urlpatterns=[
    path("",views.index, name="index"), path('contact/', ContactView.as_view(), name='contact'),
    
]

portfolio_project/portfolio_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("portfolio_app.urls")),
    path("", RedirectView.as_view(url="portfolio_app/")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio_project/portfolio_app/models.py
from django.db import models

# Create your models here.

# Profileを管理するモデル
class Profile(models.Model):
    name = models.CharField(max_length=20)
    birth_date = models.DateField()
    location = models.CharField(max_length=50)
    education = models.CharField(max_length=50)
    profile_image = models.ImageField(upload_to='images/')
    blog = models.URLField(blank=True, verbose_name='Blog')
    github = models.URLField(blank=True, verbose_name='GitHub')
    # 必要に応じて他SNSも追加可

    def __str__(self):
        return self.name

# Skills を管理するモデル
class MySkill(models.Model):
    skill_name = models.CharField(max_length=100, unique=True) 
    skill_learning_period = models.CharField(max_length=100)
    skill_level = models.IntegerField()
    skill_description = models.TextField()  # 学習内容の詳細を記述する
    skill_image = models.ImageField(upload_to='images/')  # 画像をアップロードする
    
    class Meta:
      db_table = 'my_skill' 

# Qualifications を管理するモデル
class MyQualification(models.Model):
    qualification_name = models.CharField(max_length=100, unique=True)
    qualification_acquisition_date = models.CharField(max_length=100) # 取得日 
    
    class Meta:
      db_table = 'my_qualification'

# Apps を管理するモデル
class App(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    link = models.URLField()
    image =models.ImageField(blank=True , upload_to='images/')

    def __str__(self):
        return self.title

portfolio_project/portfolio_app/forms.py
from django import forms

class ContactForm(forms.Form):
    name = forms.CharField(max_length=100, label='name')
    email = forms.EmailField(label='email')
    message = forms.CharField(widget=forms.Textarea, label='message')

portfolio_project/portfolio_app/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.views import View
from .models import Profile,MySkill, MyQualification,App
from .forms import ContactForm
from django.shortcuts import get_object_or_404
# Create your views here.

def get_index_context(form=None):
    profile = Profile.objects.first()
    skills = MySkill.objects.all()
    qualifications = MyQualification.objects.all()
    apps = App.objects.all()
    context = {
        "profile": profile,
        "skills": skills,
        "qualifications": qualifications,
        "apps" : apps,
        "form": form or ContactForm(),
    }
    return context


def index(request):
    context = get_index_context()
    return render(request, "portfolio/index.html", context)

class ContactView(View):
    def get(self, request):
        context = get_index_context()
        return render(request, "portfolio/index.html", context)

    def post(self, request):
        form = ContactForm(request.POST)
        if form.is_valid():
            # フォームのデータを処理する
            messages.success(request, "送信が完了しました！")
            return redirect('portfolio_app:index')
        context = get_index_context(form)
        return render(request, "portfolio/index.html", context)

portfolio_project/templates/portfolio/index.html
{% extends "portfolio/portfolio_base.html" %}
{% load static %}
{% load custom_filters %}
{% block title %}
  Portfolio
{% endblock title %}
{% block content %}
  <div class="hero" id="hero">
    <strong>Takumi Dowaki's Portfolio</strong>
    {% if messages %}
      <div class="global-success-message">
        {% for message in messages %}{{ message }}{% endfor %}
      </div>
    {% endif %}
    <div class="hero-particles" id="particles-js"></div>
    <video autoplay loop muted preload>
      <source src="{% static "videos/cow2.mp4" %}"
              type="video/mp4"
              alt="Hero image" />
    </video>
  </div>
  <section class="section" id="profile">
    <h1 class="section-headline">Profile</h1>
    <div class="profile profile-3col">
      <div class="profile-top">
        <div class="profile-top-left">
          <img src="{{ profile.profile_image.url }}"
               class="profile-image"
               alt="profile-img"
               width="600"
               height="400">
        </div>
        <div class="profile-top-right">
          <div class="profile-name">{{ profile.name }}</div>
          <div class="profile-basic">
            <span>誕生日：{{ profile.birth_date }}</span>
            <br>
            <span>出身地：{{ profile.location }}</span>
          </div>
          <div class="profile-card profile-links">
            <ul class="profile-link-list">
              {% if profile.blog %}
                <li>
                  <a href="{{ profile.blog }}"
                     class="profile-link-btn profile-blog"
                     target="_blank">Blog</a>
                </li>
              {% endif %}
              {% if profile.github %}
                <li>
                  <a href="{{ profile.github }}"
                     class="profile-link-btn profile-github"
                     target="_blank">GitHub</a>
                </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </div>
      <div class="profile-bottom">
        <div class="profile-card profile-about">
          <h2 class="profile-headline">
            <span>📝 About Me</span>
          </h2>
          <div>
            <div class="profile-strong">
              <span class="profile-strong-text">「Just Do It !!」とにかくやってみる</span>
              <br>
              <span class="profile-strong-subtext">をモットーに日々、色んな事にチャレンジしています</span>
            </div>
            去年は、ゼロからプログラミングをはじめ、数カ月でPythonを習得し卒業研究でアウトプット
            <br>
            そして、プログラミング以外には応用情報技術者試験やボランティアなど課外活動にもチャレンジ
            <br>
            <br>
            大学では土木工学を専攻しており、大阪市の地下水環境についてGIS（Geographic Information System）を専門に、研究しています。
            授業の合間や休日に、プログラミングスキル向上に励んでいます！！
          </div>
        </div>
        <div class="profile-card profile-hobbies">
          <h2 class="profile-headline">
            <span>趣味 Hobby</span>
          </h2>
          <ul>
            <li>料理が好きで得意料理はスパニッシュオムレツ</li>
            <li>とにかく散歩と自然が好きで色んな所に行きたい</li>
            <li>プログラミング：気づいたら１日が終わってるくらい没頭</li>
          </ul>
        </div>
        <div class="profile-card profile-interests">
          <h2 class="profile-headline">
            <span>今後挑戦したいこと</span>
          </h2>
          <ul>
            <li>Kaggleでメダルを獲得！！</li>
            <li>フロントエンドの技術習得に向けてWebアプリ構築中</li>
            <li>プログラミングで実務経験を積みたい！</li>
          </ul>
        </div>
      </div>
    </div>
  </section>
  <section class="section section-secondary" data-aos="fade-up">
    <h1 class="section-headline" id="skill">Skill & Qualification</h1>
    <h2 class="section-subheadline">Skills</h2>
    <ul class="grid grid-col-4">
      {% for skill in skills %}
        <li class="grid-item" data-aos="fade-up">
          <dl class="skill">
            <dt class="skill-headline">{{ skill.skill_name }}</dt>
            <dd class="skill-img">
              <img src="{{ skill.skill_image.url }}"
                   width="140"
                   height="140"
                   alt="{{ skill.skill_name }} image">
            </dd>
            <dd class="skill-period">
              学習期間：{{ skill.skill_learning_period }}
            </dd>
            <dd class="skill-level">
              習熟度：{{ skill.skill_level|skill_level_to_stars }}
            </dd>
            <dd class="skill-description">
              {{ skill.skill_description }}
            </dd>
          </dl>
        </li>
      {% endfor %}
    </ul>
    <h2 class="section-subheadline">Qualification</h2>
    <table class="qualification" data-aos="fade-up">
      <thead>
        <tr>
          <th>資格名</th>
          <th>取得年月</th>
        </tr>
      </thead>
      <tbody>
        {% for qualification in qualifications %}
          <tr data-aos="fade-up">
            <td>{{ qualification.qualification_name }}</td>
            <td>{{ qualification.qualification_acquisition_date }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </section>
  <section class="section" id="apps">
    <h1 class="section-headline">Apps</h1>
    <p class="section-description">作成したWebアプリを掲載する予定になります。現在作成途中</p>
    <div class="apps-grid">
      {% for app in apps %}
        <div class="app-item" data-aos="fade-up">
          <h2 class="app-title">{{ app.title }}</h2>
          <p class="app-description">{{ app.description }}</p>
          <a href="{{ app.link }}" class="app-link" target="_blank">View App</a>
        </div>
      {% endfor %}
    </div>
  </section>
  <section class="section">
    <h1 class="section-headline" id="contact">Contact</h1>
    <div class="contact-form">
      <form method="post" action="{% url 'portfolio_app:contact' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">送信</button>
      </form>
    </div>
  </section>
{% endblock content %}
{% block scripts %}
  <script src="{% static 'js/particles.js' %}"></script>
  <script src="{% static 'js/app.js' %}"></script>
  <script>
    document.getElementById('contact-form').addEventListener('submit', function() {
      document.getElementById('loading-spinner').style.display = 'block';
    });
  </script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.js"></script>
  <script>AOS.init();</script>
{% endblock scripts %}

portfolio_project/templates/portfolio/portfolio_base.html
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>
      {% block title %}
        Portfolio
      {% endblock title %}
    </title>
    <meta name="description" content="Your description here" />
    <meta name="keywords" content="keyword1, keyword2, keyword3" />
    {% load static %}
    <link rel="icon" href="{% static 'favicon.ico' %}">
    <link rel="stylesheet" href="{% static 'css/reset.css' %}" />
    <link rel="stylesheet" href="{% static 'css/base.css' %}" />
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.css" />
  </head>
  <body>
    <nav class="nav">
      <ul>
        <li>
          <a href="#hero">Home</a>
        </li>
        <li>
          <a href="#profile">Profile</a>
        </li>
        <li>
          <a href="#skill">Skill</a>
        </li>
        <li>
          <a href="#blog">Blog</a>
        </li>
        <li>
          <a href="#app">App</a>
        </li>
        <li>
          <a href="#contact">Contact</a>
        </li>
      </ul>
    </nav>
    <div class="main-container">
      {% block content %}
      {% endblock content %}
    </div>
    {% block scripts %}
    {% endblock scripts %}
  </body>
</html>